const canvas = document.querySelector("#lattice-canvas");
const ctx = canvas.getContext("2d");

const ui = {
  level: document.querySelector("#level-readout"),
  moves: document.querySelector("#moves-readout"),
  lit: document.querySelector("#lit-readout"),
  par: document.querySelector("#par-readout"),
  progressMeter: document.querySelector("#progress-meter"),
  overlay: document.querySelector("#overlay"),
  overlayKicker: document.querySelector("#overlay-kicker"),
  overlayTitle: document.querySelector("#overlay-title"),
  overlayCopy: document.querySelector("#overlay-copy"),
  primaryAction: document.querySelector("#primary-action"),
  hintButton: document.querySelector("#hint-button"),
  undoButton: document.querySelector("#undo-button"),
  resetButton: document.querySelector("#reset-button")
};

const WORLD = { width: 720, height: 720 };

// Each level is generated by scrambling a fully lit lattice, so every puzzle is
// guaranteed solvable: re-applying the scramble clicks restores the solved board.
const LEVELS = [
  { size: 4, scramble: 4, par: 4 },
  { size: 5, scramble: 6, par: 6 },
  { size: 5, scramble: 9, par: 8 },
  { size: 6, scramble: 11, par: 10 },
  { size: 6, scramble: 14, par: 12 }
];

const BASE_SEED = 0x9e3779b1;

let state = createInitialState();
let lastTime = performance.now();

function createInitialState() {
  return {
    mode: "menu",
    levelIndex: 0,
    size: LEVELS[0].size,
    par: LEVELS[0].par,
    grid: [],
    remaining: [],
    history: [],
    cursor: { row: 0, col: 0 },
    moves: 0,
    beams: [],
    cellFx: [],
    hintCell: null,
    hintUntil: 0,
    time: 0,
    solvedLevels: 0
  };
}

function startLevel(index) {
  const config = LEVELS[index];
  const size = config.size;
  const rng = mulberry32(BASE_SEED + (index + 1) * 0x85ebca77);

  // Begin from a fully lit lattice, then scramble it with cross-toggle clicks.
  const grid = makeGrid(size, true);
  const remaining = makeGrid(size, false);

  let applied = 0;
  let guard = 0;
  while (applied < config.scramble || isAllLit(grid)) {
    const row = Math.floor(rng() * size);
    const col = Math.floor(rng() * size);
    applyCross(grid, row, col);
    remaining[row][col] = !remaining[row][col];
    applied += 1;
    guard += 1;
    if (guard > 500) {
      break;
    }
  }

  state.levelIndex = index;
  state.size = size;
  state.par = config.par;
  state.grid = grid;
  state.remaining = remaining;
  state.history = [];
  state.cursor = { row: 0, col: 0 };
  state.moves = 0;
  state.beams = [];
  state.cellFx = [];
  state.hintCell = null;
  state.hintUntil = 0;
  state.mode = "playing";
  hideOverlay();
  updateUi();
}

function makeGrid(size, value) {
  return Array.from({ length: size }, () => Array.from({ length: size }, () => value));
}

// A click sends light down its whole row and column. Every lumen the beams pass
// through flips once (the clicked cell included).
function applyCross(grid, row, col) {
  const size = grid.length;
  for (let i = 0; i < size; i += 1) {
    grid[row][i] = !grid[row][i];
  }
  for (let i = 0; i < size; i += 1) {
    if (i !== row) {
      grid[i][col] = !grid[i][col];
    }
  }
}

function isAllLit(grid) {
  return grid.every((line) => line.every((cell) => cell));
}

function litCount(grid) {
  let total = 0;
  for (const line of grid) {
    for (const cell of line) {
      if (cell) {
        total += 1;
      }
    }
  }
  return total;
}

function clickCell(row, col, fromUndo = false) {
  if (state.mode !== "playing") {
    return;
  }
  if (row < 0 || col < 0 || row >= state.size || col >= state.size) {
    return;
  }

  applyCross(state.grid, row, col);
  state.remaining[row][col] = !state.remaining[row][col];
  spawnBeams(row, col);
  pulseCross(row, col);

  if (fromUndo) {
    state.moves = Math.max(0, state.moves - 1);
  } else {
    state.history.push({ row, col });
    state.moves += 1;
  }

  if (state.hintCell && state.hintCell.row === row && state.hintCell.col === col) {
    state.hintCell = null;
  }

  if (isAllLit(state.grid)) {
    winLevel();
  }

  updateUi();
}

function undo() {
  if (state.mode !== "playing" || state.history.length === 0) {
    return;
  }
  const last = state.history.pop();
  clickCell(last.row, last.col, true);
}

function reset() {
  if (state.mode === "won" || state.mode === "menu") {
    startLevel(state.levelIndex);
    return;
  }
  startLevel(state.levelIndex);
}

function showHint() {
  if (state.mode !== "playing") {
    return;
  }
  for (let row = 0; row < state.size; row += 1) {
    for (let col = 0; col < state.size; col += 1) {
      if (state.remaining[row][col]) {
        state.hintCell = { row, col };
        state.hintUntil = state.time + 2.4;
        updateUi();
        return;
      }
    }
  }
  // Nothing left in the tracked solution means the board is already solved.
  state.hintCell = null;
}

function winLevel() {
  state.mode = "won";
  state.beams = [];
  state.solvedLevels = Math.max(state.solvedLevels, state.levelIndex + 1);

  const isFinal = state.levelIndex >= LEVELS.length - 1;
  const rating = state.moves <= state.par ? "Clean solve — at or under par." : `Solved in ${state.moves} moves (par ${state.par}).`;

  if (isFinal) {
    showOverlay(
      "Lattice array synchronized",
      `Every node in the array is aligned. ${rating} You mapped all ${LEVELS.length} lattices.`,
      "Replay from lattice 1",
      () => startLevel(0)
    );
  } else {
    showOverlay(
      `Lattice ${state.levelIndex + 1} synchronized`,
      `All lumens are lit. ${rating}`,
      "Next lattice",
      () => startLevel(state.levelIndex + 1)
    );
  }
}

function moveCursor(dRow, dCol) {
  if (state.mode !== "playing") {
    return;
  }
  state.cursor.row = clamp(state.cursor.row + dRow, 0, state.size - 1);
  state.cursor.col = clamp(state.cursor.col + dCol, 0, state.size - 1);
}

function spawnBeams(row, col) {
  state.beams.push({ type: "row", index: row, born: state.time });
  state.beams.push({ type: "col", index: col, born: state.time });
  state.beams = state.beams.filter((beam) => state.time - beam.born < 0.5);
}

function pulseCross(row, col) {
  const size = state.size;
  for (let i = 0; i < size; i += 1) {
    state.cellFx.push({ row, col: i, born: state.time });
    if (i !== row) {
      state.cellFx.push({ row: i, col, born: state.time });
    }
  }
  if (state.cellFx.length > 240) {
    state.cellFx.splice(0, state.cellFx.length - 240);
  }
}

function update(dt) {
  state.time += dt;
  state.beams = state.beams.filter((beam) => state.time - beam.born < 0.5);
  state.cellFx = state.cellFx.filter((fx) => state.time - fx.born < 0.45);
  if (state.hintCell && state.time > state.hintUntil) {
    state.hintCell = null;
  }
}

function geometry() {
  const size = state.size;
  const margin = 64;
  const span = Math.min(WORLD.width, WORLD.height) - margin * 2;
  const gap = span * 0.06 / size;
  const cell = (span - gap * (size - 1)) / size;
  const originX = (WORLD.width - span) / 2;
  const originY = (WORLD.height - span) / 2;
  return { size, margin, span, gap, cell, originX, originY };
}

function cellRect(geo, row, col) {
  return {
    x: geo.originX + col * (geo.cell + geo.gap),
    y: geo.originY + row * (geo.cell + geo.gap),
    w: geo.cell,
    h: geo.cell
  };
}

function cellAtPoint(worldX, worldY) {
  const geo = geometry();
  for (let row = 0; row < geo.size; row += 1) {
    for (let col = 0; col < geo.size; col += 1) {
      const rect = cellRect(geo, row, col);
      if (worldX >= rect.x && worldX <= rect.x + rect.w && worldY >= rect.y && worldY <= rect.y + rect.h) {
        return { row, col };
      }
    }
  }
  return null;
}

function render() {
  ctx.clearRect(0, 0, WORLD.width, WORLD.height);
  drawBackground();

  const geo = geometry();
  drawBeams(geo);
  drawCells(geo);
  drawCursor(geo);
}

function drawBackground() {
  const gradient = ctx.createLinearGradient(0, 0, WORLD.width, WORLD.height);
  gradient.addColorStop(0, "#070b16");
  gradient.addColorStop(0.6, "#0a0a14");
  gradient.addColorStop(1, "#120a1c");
  ctx.fillStyle = gradient;
  ctx.fillRect(0, 0, WORLD.width, WORLD.height);

  ctx.strokeStyle = "rgba(123, 158, 255, 0.06)";
  ctx.lineWidth = 1;
  for (let x = 0; x <= WORLD.width; x += 36) {
    ctx.beginPath();
    ctx.moveTo(x, 0);
    ctx.lineTo(x, WORLD.height);
    ctx.stroke();
  }
  for (let y = 0; y <= WORLD.height; y += 36) {
    ctx.beginPath();
    ctx.moveTo(0, y);
    ctx.lineTo(WORLD.width, y);
    ctx.stroke();
  }
}

function drawBeams(geo) {
  for (const beam of state.beams) {
    const life = 1 - (state.time - beam.born) / 0.5;
    if (life <= 0) {
      continue;
    }
    ctx.fillStyle = `rgba(124, 246, 255, ${0.16 * life})`;
    if (beam.type === "row") {
      const rect = cellRect(geo, beam.index, 0);
      ctx.fillRect(geo.originX - geo.gap, rect.y - geo.gap * 0.5, geo.span + geo.gap * 2, rect.h + geo.gap);
    } else {
      const rect = cellRect(geo, 0, beam.index);
      ctx.fillRect(rect.x - geo.gap * 0.5, geo.originY - geo.gap, rect.w + geo.gap, geo.span + geo.gap * 2);
    }
  }
}

function fxAt(row, col) {
  let strongest = 0;
  for (const fx of state.cellFx) {
    if (fx.row === row && fx.col === col) {
      const life = 1 - (state.time - fx.born) / 0.45;
      if (life > strongest) {
        strongest = life;
      }
    }
  }
  return strongest;
}

function drawCells(geo) {
  for (let row = 0; row < geo.size; row += 1) {
    for (let col = 0; col < geo.size; col += 1) {
      const rect = cellRect(geo, row, col);
      const lit = state.grid[row][col];
      const fx = fxAt(row, col);
      const radius = Math.max(8, geo.cell * 0.18);

      roundRect(rect.x, rect.y, rect.w, rect.h, radius);

      if (lit) {
        const glow = ctx.createRadialGradient(
          rect.x + rect.w / 2,
          rect.y + rect.h / 2,
          rect.w * 0.1,
          rect.x + rect.w / 2,
          rect.y + rect.h / 2,
          rect.w * 0.75
        );
        glow.addColorStop(0, "rgba(124, 246, 255, 0.95)");
        glow.addColorStop(0.6, "rgba(86, 142, 255, 0.55)");
        glow.addColorStop(1, "rgba(86, 142, 255, 0.12)");
        ctx.fillStyle = glow;
        ctx.fill();
        ctx.strokeStyle = "rgba(196, 250, 255, 0.85)";
      } else {
        ctx.fillStyle = "rgba(255, 255, 255, 0.04)";
        ctx.fill();
        ctx.strokeStyle = "rgba(123, 158, 255, 0.22)";
      }
      ctx.lineWidth = 2;
      ctx.stroke();

      if (fx > 0) {
        roundRect(rect.x, rect.y, rect.w, rect.h, radius);
        ctx.strokeStyle = `rgba(168, 255, 198, ${0.7 * fx})`;
        ctx.lineWidth = 3;
        ctx.stroke();
      }

      const isHint = state.hintCell && state.hintCell.row === row && state.hintCell.col === col;
      if (isHint) {
        const pulse = 0.5 + Math.sin(state.time * 7) * 0.4;
        roundRect(rect.x - 4, rect.y - 4, rect.w + 8, rect.h + 8, radius + 3);
        ctx.strokeStyle = `rgba(255, 209, 102, ${pulse})`;
        ctx.lineWidth = 4;
        ctx.stroke();
      }
    }
  }
}

function drawCursor(geo) {
  if (state.mode !== "playing") {
    return;
  }
  const rect = cellRect(geo, state.cursor.row, state.cursor.col);
  const radius = Math.max(8, geo.cell * 0.18);
  roundRect(rect.x - 2, rect.y - 2, rect.w + 4, rect.h + 4, radius + 2);
  ctx.strokeStyle = "rgba(244, 247, 255, 0.85)";
  ctx.setLineDash([10, 8]);
  ctx.lineWidth = 2;
  ctx.stroke();
  ctx.setLineDash([]);
}

function roundRect(x, y, w, h, r) {
  const radius = Math.min(r, w / 2, h / 2);
  ctx.beginPath();
  ctx.moveTo(x + radius, y);
  ctx.arcTo(x + w, y, x + w, y + h, radius);
  ctx.arcTo(x + w, y + h, x, y + h, radius);
  ctx.arcTo(x, y + h, x, y, radius);
  ctx.arcTo(x, y, x + w, y, radius);
  ctx.closePath();
}

function updateUi() {
  const total = state.size * state.size;
  const lit = litCount(state.grid);
  ui.level.textContent = `${state.levelIndex + 1} / ${LEVELS.length}`;
  ui.moves.textContent = String(state.moves);
  ui.lit.textContent = `${lit} / ${total}`;
  ui.par.textContent = String(state.par);
  ui.progressMeter.style.width = `${Math.round(lit / total * 100)}%`;
  ui.undoButton.disabled = state.mode !== "playing" || state.history.length === 0;
  ui.hintButton.disabled = state.mode !== "playing";

  canvas.dataset.mode = state.mode;
  canvas.dataset.level = String(state.levelIndex + 1);
  canvas.dataset.moves = String(state.moves);
  canvas.dataset.lit = String(lit);
  canvas.dataset.total = String(total);
  canvas.dataset.solved = String(lit === total);
}

function loop(now) {
  const dt = Math.min(0.033, (now - lastTime) / 1000);
  lastTime = now;
  update(dt);
  render();
  requestAnimationFrame(loop);
}

function showOverlay(title, copy, actionText, action) {
  ui.overlay.classList.remove("hidden");
  ui.overlayKicker.textContent = "Observation 002 / Game 002";
  ui.overlayTitle.textContent = title;
  ui.overlayCopy.textContent = copy;
  ui.primaryAction.replaceWith(ui.primaryAction.cloneNode(true));
  ui.primaryAction = document.querySelector("#primary-action");
  ui.primaryAction.textContent = actionText;
  ui.primaryAction.addEventListener("click", action);
}

function hideOverlay() {
  ui.overlay.classList.add("hidden");
}

function screenToWorld(clientX, clientY) {
  const rect = canvas.getBoundingClientRect();
  return {
    x: (clientX - rect.left) / rect.width * WORLD.width,
    y: (clientY - rect.top) / rect.height * WORLD.height
  };
}

function clamp(value, min, max) {
  return Math.max(min, Math.min(max, value));
}

function mulberry32(seed) {
  return function next() {
    seed |= 0;
    seed = seed + 0x6d2b79f5 | 0;
    let t = Math.imul(seed ^ seed >>> 15, 1 | seed);
    t = t + Math.imul(t ^ t >>> 7, 61 | t) ^ t;
    return ((t ^ t >>> 14) >>> 0) / 4294967296;
  };
}

canvas.addEventListener("pointerdown", (event) => {
  if (state.mode !== "playing") {
    return;
  }
  const point = screenToWorld(event.clientX, event.clientY);
  const cell = cellAtPoint(point.x, point.y);
  if (cell) {
    state.cursor = { row: cell.row, col: cell.col };
    clickCell(cell.row, cell.col);
  }
});

window.addEventListener("keydown", (event) => {
  const key = event.key.toLowerCase();
  const handled = [
    "arrowup", "arrowdown", "arrowleft", "arrowright",
    " ", "enter", "w", "a", "s", "d", "h", "u", "r"
  ];
  if (handled.includes(key)) {
    event.preventDefault();
  }

  if (state.mode === "menu" && (key === "enter" || key === " ")) {
    startLevel(0);
    return;
  }
  if (state.mode === "won" && (key === "enter" || key === " ")) {
    ui.primaryAction.click();
    return;
  }

  if (key === "arrowup" || key === "w") {
    moveCursor(-1, 0);
  }
  if (key === "arrowdown" || key === "s") {
    moveCursor(1, 0);
  }
  if (key === "arrowleft" || key === "a") {
    moveCursor(0, -1);
  }
  if (key === "arrowright" || key === "d") {
    moveCursor(0, 1);
  }
  if (key === "enter" || key === " ") {
    clickCell(state.cursor.row, state.cursor.col);
  }
  if (key === "h") {
    showHint();
  }
  if (key === "u") {
    undo();
  }
  if (key === "r") {
    reset();
  }
});

ui.hintButton.addEventListener("click", showHint);
ui.undoButton.addEventListener("click", undo);
ui.resetButton.addEventListener("click", reset);
ui.primaryAction.addEventListener("click", () => startLevel(0));

window.__lumenLatticeQA = {
  start: () => startLevel(0),
  startLevel,
  getSnapshot() {
    return {
      mode: state.mode,
      level: state.levelIndex + 1,
      size: state.size,
      moves: state.moves,
      lit: litCount(state.grid),
      total: state.size * state.size,
      solved: isAllLit(state.grid),
      remainingMoves: state.remaining.flat().filter(Boolean).length
    };
  },
  // Replays the tracked solution for the current board; always reaches all-lit.
  autoSolve() {
    const pending = [];
    for (let row = 0; row < state.size; row += 1) {
      for (let col = 0; col < state.size; col += 1) {
        if (state.remaining[row][col]) {
          pending.push({ row, col });
        }
      }
    }
    for (const move of pending) {
      clickCell(move.row, move.col);
    }
    return isAllLit(state.grid);
  }
};

showOverlay(
  "Light the lattice",
  "Press any node to fire light down its row and column. Every lumen the beams cross flips. Light every node to synchronize the lattice.",
  "Start lattice 1",
  () => startLevel(0)
);
requestAnimationFrame(loop);
